kind: "Application"
apiVersion: "nais.io/v1alpha1"
metadata:
  name: story-api
  namespace: nada
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  labels:
    team: nada
spec:
  accessPolicy:
    outbound:
      rules:
        - application: nada-backend
  image: "{{ image }}"
  port: 8080
  replicas:
    min: 2
    max: 3
  env:
    - name: STORY_BUCKET
      value: nada-ekstern-markedsplass-dev
    - name: NADA_BACKEND_URL
      value: http://nada-backend.nada.svc.cluster.local/internal/teamtokens
  envFrom:
    - secret: story-api
  ingresses:
    - "https://nada.ekstern.dev.nav.no/api"
    - "https://data.ekstern.dev.nav.no/api"
  gcp:
    buckets:
      - name: nada-ekstern-markedsplass-dev
        publicAccessPrevention: false
        uniformBucketLevelAccess: true
