name: build and push
on: 
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
    - uses: actions/checkout@v5
    - uses: nais/docker-build-push@v0
      id: docker-build-push
      with:
        team: nada

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [build-and-push]
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v5
    - name: Deploy to dev
      uses: nais/deploy/actions/deploy@v2
      env:
        CLUSTER: dev-gcp
        RESOURCE: .nais/dev.yaml
        VAR: image=${{ needs.build-and-push.outputs.image }}
    - name: Deploy to prod
      uses: nais/deploy/actions/deploy@v2
      env:
        CLUSTER: prod-gcp
        RESOURCE: .nais/prod.yaml
        VAR: image=${{ needs.build-and-push.outputs.image }}
